import Footer from '@/components/Footer/Footer'
import Navbar from '@/components/Navbar/Navbar'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Newsy | Superfast News',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} lg:overflow-x-hidden bg-gray-100`}>
        <Navbar/>
          {children}
        <Footer/>
        </body>
    </html>
  )
}
